spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
mail:
  address:
    admin: admin@gmail.com

jwt:
  key: jwt123412341234123412341234123412341234123412341234
  access-token-expiration-minutes: 300000
  refresh-token-expiration-minutes: 420000

