spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  redis:
    host: localhost  # 배포 시 ec2 주소 사용
    port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 24201237268-a4n4us4gv91auvj1uhhnu6ua3trngvj4.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

mail:
  address:
    admin: admin@gmail.com

jwt:
  key: jwt123412341234123412341234123412341234123412341234
  access-token-expiration-minutes: 3000
  refresh-token-expiration-minutes: 4200000

