spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
#    url: jdbc:h2:mem:test
    url: jdbc:mysql://pre031-database.cjdwiha5rdwq.ap-northeast-2.rds.amazonaws.com:13306/pre031?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: admin
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 24201237268-a4n4us4gv91auvj1uhhnu6ua3trngvj4.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

mail:
  address:
    admin: admin@gmail.com

jwt:
  key: jwt123412341234123412341234123412341234123412341234
  access-token-expiration-minutes: 3000
  refresh-token-expiration-minutes: 4200000

